In [1]:
import numpy as np

In [5]:
arr = np.arange(1,11)

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[0]

1

In [8]:
arr[1:5]

array([2, 3, 4, 5])

In [9]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [10]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5]=100

In [13]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [14]:
slice_of_arr = arr[0:5]

In [15]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [16]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [17]:
slice_of_arr[:]= 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
 arr_copy = arr.copy()

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
#2D dimensional array

In [25]:
arr_2d = np.array([[5,10,15],[6,12,18],[4,8,12]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [ 6, 12, 18],
       [ 4,  8, 12]])

In [27]:
arr_2d.shape

(3, 3)

In [28]:
arr_2d[2]

array([ 4,  8, 12])

In [30]:
arr_2d[1,1]

12

In [31]:
arr_2d[:2,1:]

array([[10, 15],
       [12, 18]])

In [32]:
arr = np.arange(1,11)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
bool_arr = arr>4

In [36]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])