In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
len(np.linspace(0,10,11))

11

In [29]:
np.random.rand(5,2)

array([[0.8818097 , 0.31878575],
       [0.47874186, 0.24094558],
       [0.5004292 , 0.93549227],
       [0.46828911, 0.63946726],
       [0.21181472, 0.879507  ]])

In [30]:
np.random.randn(10)

array([ 0.16170652, -0.49250915, -1.84698742, -0.56487971, -0.40773624,
       -0.0362134 ,  0.40189381, -0.44230728,  0.82601731,  0.39098986])

In [31]:
np.random.randn(2,3)

array([[ 0.20895807,  2.20293683,  0.37053486],
       [-0.50958038,  0.2834425 ,  0.78631869]])

In [34]:
np.random.randint(0,101,(4,5))

array([[ 4, 89, 72, 57, 55],
       [ 9, 78, 15, 49, 91],
       [62, 30, 34, 89, 50],
       [65, 50, 21, 24, 87]])

In [35]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [36]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [37]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [38]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [39]:
arr= np.arange(0,25)

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
ranarr = np.random.randint(0,101,10)

In [46]:
ranarr

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [47]:
ranarr.max()

92

In [48]:
ranarr.min()

4

In [49]:
ranarr.argmax()

7

In [51]:
ranarr.argmin()

3

In [53]:
ranarr.dtype

dtype('int32')

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
arr.shape

(25,)

In [56]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
arr.shape

(25,)

In [59]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])