In [1]:
import numpy as np

In [2]:
arr= np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr +5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [6]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr / arr

C:\Users\Alira\AppData\Local\Temp\ipykernel_17292\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [13]:
np.log(arr)

C:\Users\Alira\AppData\Local\Temp\ipykernel_17292\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [14]:
arr.sum()

45

In [15]:
arr.mean()

4.5

In [16]:
arr.var()

8.25

In [17]:
arr.max()

9

In [18]:
arr.std()

2.8722813232690143

In [21]:
arr_2d = np.arange(0,25).reshape(5,5)

In [22]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
 arr_2d.shape

(5, 5)

In [26]:
arr_2d.sum()

300

In [27]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [28]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [29]:
#create an array of 10 zeros
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
#Create an array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [33]:
#Create an array of integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [36]:
#create an even integer from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [38]:
#Create a 3x3 matrix with vallues ranging from 0 to 8
arr = np.arange(9)
arr.reshape(3,3)
#np.arange(9).reshape(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#Numpy to generate no. btw 0 and 1
np.random.rand(1)

array([0.23426301])

In [5]:
import numpy as np
#NUmpy to generate array of 25 random no.from a Standard Normal Distribution
np.random.randn(25)

array([-1.29731246,  0.56335331,  1.88483919, -0.73239095, -0.12185589,
        1.47998357, -0.27044535,  0.74491098,  0.18456378, -1.73690494,
       -0.83260165, -0.02848927, -1.02592829, -0.438254  ,  0.22653141,
        0.20996871,  0.21482675,  1.49892378, -1.28158591,  0.01295195,
       -0.51502328,  1.48383976, -1.24013572,  0.74540611, -0.03209252])

In [8]:
arr = np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [10]:
#Create an array of 20 linearly spaced points btw 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [11]:
#NUmpy Indexing and Selection
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
mat[2:,1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
mat[3,4]

20

In [24]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [26]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [27]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
mat.sum()

325

In [29]:
#Get Standard Deviation of values in mat
mat.std()

7.211102550927978

In [31]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [32]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])